#ifndef SL_CONNECT_HOST_VERSION_H
#define SL_CONNECT_HOST_VERSION_H

#ifndef SL_CONNECT_HOST_VERSION_MAJOR
#define SL_CONNECT_HOST_VERSION_MAJOR 0
#endif

#ifndef SL_CONNECT_HOST_VERSION_MINOR
#define SL_CONNECT_HOST_VERSION_MINOR 1
#endif

#ifndef SL_CONNECT_HOST_VERSION_PATCH
#define SL_CONNECT_HOST_VERSION_PATCH 0
#endif

#define FORMAT_CONNECT_HOST_VERSION(a, b, c) (((a) << 16) + ((b) << 8) +  (c))
#define SL_CONNECT_HOST_VERSION FORMAT_CONNECT_HOST_VERSION(SL_CONNECT_HOST_VERSION_MAJOR, SL_CONNECT_HOST_VERSION_MINOR, SL_CONNECT_HOST_VERSION_PATCH)

#endif  // SL_CONNECT_HOST_VERSION_H
